{% set name = "libatomic_ops" %}
{% set version = "7.6.4" %}
{% set sha256 = "5b823d5a685dd70caeef8fc50da7d763ba7f6167fe746abca7762e2835b3dd4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h
    - test -e $PREFIX/lib/libatomic_ops.a

about:
  home: https://github.com/ivmai/libatomic_ops
  license: Custom
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
    - saraedum
