{% set name = "libatomic_ops" %}
{% set version = "7.6.10" %}
{% set sha256 = "587edf60817f56daf1e1ab38a4b3c729b8e846ff67b4f62a6157183708f099af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h
    - test -e $PREFIX/lib/libatomic_ops.a

about:
  home: https://github.com/ivmai/libatomic_ops
  license: Custom
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
    - saraedum
