travis:
  secure:
    BINSTAR_TOKEN: j/ZXRkQV9wCLbkgblrDxObIMtpZiJTfyBVcIG7ZZ0yFQK23VU3nSv79OJdabkGOIEHvplz6xuhf9yiuDuAmPR9QKZg59G1CqEI/lCDl77E4wNkK5m2IVR8trTRaVLA2kE7101f9IuXxAUd498LO88JPG6LuXKsaOKHnWJXvVI0y0CVSg5F2B6XzaCyMZDVr5pywhUpS/U/XoVSfvkmlPzj2tTd3PGy1qSH+jDj5jF7N9mJf/DVE+xbVvnSrw1I3jUTI2VphcSw71Ou9FCqoj6ebrJ8JLfyJYO77HXsGAL/w4w7Z+t6XcmefCXg0FUnGBQokc8HepGCQThINj5uHx/osFs/FyGBG/KXRUmJmd7Q9ePz1DsnKqBFAjRaot6X/JNNZu+F6PaNSA3g7vLNJ//xv+RoqqXk+aSGAj7bX2wSV9iUXfNXvdnhQdh9EJB2VeYaO7bJGd7HE4IqTu1Coz5E8uoYkeazQ0Y5MN3wGVe3wLW++qtmBsnBQnhSiiDcEWSqeLM7TsXqoHeECj3/9dwbFgLALxA7JMpA0cS4OocWAA5d9ppElNcYGOLNB6vYy7IYHURlGoMv7kiSM5gnv94r9CuZLYJq1xhcaPSz51TylB+NpwJah/uE8UECZnqE024t8njikCy4gUcSvnvJT1KUCW8jnSfmj5Bsx2sSfTfYg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
