appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: jkZxooMfKxI3hrc5ClXxej5NDdAkt7lr5tbXAGIKtZ7mhfnP+2YWfX8ar6XBKZND2NxSLpIgzQg+WTldp379Lks3WzWc8raBqf5Vh47y3b8gM1Jy7DAVfJDyndzPoStl+75/EwGXCqhlYysJ6UY55qukYeVoce41PSMZCBwh2ScGFlBEoYWb4ttE83MdV4kHw/yIogkam5wPlZt6vP+BnOOGWa9tol1/dLEyVSEQx3vJySp1E48yMAG5UHH0zf1+K6X4MaBz5mYqUPPL+sb7Uoy8+bL1oPqBh6kVZk1GwQ6UJ1PzPKXK6db9m+6aR//JEuK+4VTM/DwMKgQWsTsp38uEbdwqBC6SKRHEh6Lr6AcjsRSQMTnbU/QECtuOty1oOxTmUzE18VXQx9pq+WgJZcp2RLUqHc1dmhLDiyHk5KzpFE5VKTWGzBbExW9fKV7pgY+ibxSXU5LP1LlNGLdk4Z0LDhU74UQFB0uCxy8cf9A4dbTKTN1b/pfSorKI8D/yJ6/Wy17hZjEp1cUGnhaZbq2LRWlD1ZpdzYhTlz4MRXX8jYCgLon3zYsMFdMBGEp0wnrcicgurIpN3RoXT//XnKymo1jsw2XF2lPbPoR7gpngYgirrvptEM200dPCXGLYyzlp6/N0vjdS/mUqel1va66HRcGwK3OW9Yd2bYI/m+g=}
conda_forge_output_validation: true
